### ISSUE TITLE
Inline comments should not be allowed

### ISSUE THREAD

**Issue by picadoh** [jnbt/java-properties#11]
Java properties, as per [documentation](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html), do not allow inline comments.

The following should be a valid property:

`xpto=#something`

But it's being handled as xpto having the nil value as, I believe, the value is being treated as a comment.

**Comment by jnbt** [comment]
@picadoh Can you please share a example file? 

I've added a small test to the specs and there it seems to correctly parse the value even if it starts with `#` char: https://github.com/jnbt/java-properties/pull/12

**Comment by picadoh** [comment]
Hi @jnbt,

After further investigation, it seems like the problem was lying somewhere else.

FYI, anyway, If it happens that we have the following property that we load in application.rb to a properties hash:

    database.password=#mysecurepassword

And the database.yml file is actually using it, like so:

    password: <%= Rails.configuration.properties[:'database.password'] %>

The whole template is replaced by the text starting with #, which is a comment in Yaml, resulting in an empty property for database.yml.

I guess we can close this issue then. Worth adding the test here though, nice job.

Cheers,
Hugo.

**Comment by jnbt** [comment]
@picadoh  Thanks for the feedback. I merged the test. Will close this issue than.
